kitchen/urls.py
from django.urls import path

from kitchen import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="main-page"),
    path("cooks/", views.CookListView.as_view(), name="cooks-page"),
    path(
        "cooks/create/",
        views.CookCreateView.as_view(),
        name="cook-create"
    ),
    path(
        "cooks/<slug:slug>/",
        views.CookDetailView.as_view(),
        name="cook-detail-page"
    ),
    path(
        "cooks/<slug:slug>/update/",
        views.CookUpdateView.as_view(),
        name="cook-update"
    ),
    path(
        "cooks/<slug:slug>/delete/",
        views.CookDeleteView.as_view(),
        name="cook-delete"
    ),
    path(
        "dishes/",
        views.DishListView.as_view(),
        name="dishes-page"
    ),
    path(
        "dishes/<int:pk>/",
        views.DishDetailView.as_view(),
        name="dish-detail-page"
    ),
    path(
        "dishes/create/",
        views.DishCreateView.as_view(),
        name="dish-create"
    ),
    path(
        "dishes/<int:pk>/update/",
        views.DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dishes/<int:pk>/delete/",
        views.DishDeleteView.as_view(),
        name="dish-delete"
    ),
    path(
        "dishes/<int:pk>/assign/",
        views.ToggleAssignToDishView.as_view(),
        name="toggle-dish-assign"
    ),
    path(
        "dish_types/",
        views.DishTypeListView.as_view(),
        name="dish-types-page"
    ),
    path(
        "dish_types/create/",
        views.DishTypeCreateView.as_view(),
        name="dish-type-create"
    ),
    path(
        "dish_types/<int:pk>/update/",
        views.DishTypeUpdateView.as_view(),
        name="dish-type-update"
    ),
    path(
        "dish_types/<int:pk>/delete/",
        views.DishTypeDeleteView.as_view(),
        name="dish-type-delete"
    ),
    path(
        "ingredients/",
        views.IngredientListView.as_view(),
        name="ingredients-page"
    ),
    path(
        "ingredients/create/",
        views.IngredientCreateView.as_view(),
        name="ingredient-create"
    ),
    path(
        "ingredients/<int:pk>/update/",
        views.IngredientUpdateView.as_view(),
        name="ingredient-update"
    ),
    path(
        "ingredients/<int:pk>/delete/",
        views.IngredientDeleteView.as_view(),
        name="ingredient-delete"
    ),
]

app_name = "kitchen"

restaurant_mate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from debug_toolbar.toolbar import debug_toolbar_urls

from kitchen.views import LogoutView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += debug_toolbar_urls()

kitchen/forms.py
from typing import Any
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import FileExtensionValidator

from .models import Cook, Dish, Ingredient


class ProfilePictureMixin(forms.Form):
    profile_picture = forms.ImageField(
        validators=[
            FileExtensionValidator(
                allowed_extensions=["jpg", "png", "jpeg"],
            )
        ],
        widget=forms.FileInput
    )


class CookCreationForm(ProfilePictureMixin, UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "email",
            "years_of_experience",
            "profile_picture",
            "bio"
        )

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields["first_name"].required = True
        self.fields["last_name"].required = True


class CookUpdateForm(ProfilePictureMixin, forms.ModelForm):

    class Meta:
        model = Cook
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "years_of_experience",
            "profile_picture",
            "bio",
        )


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    ingredients = forms.ModelMultipleChoiceField(
        queryset=Ingredient.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Dish
        exclude = ("created_at", "updated_at",)


class CookSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label=False,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by username"
            }
        )
    )


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label=False,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name"
            }
        )
    )


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label=False,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name"
            }
        )
    )


class IngredientSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label=False,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name"
            }
        )
    )

kitchen/views.py
from typing import Any
from django.contrib.auth import logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse, reverse_lazy
from django.db.models import QuerySet

from .models import Dish, Cook, DishType, Ingredient
from .forms import (
    CookCreationForm,
    CookUpdateForm,
    DishForm,
    CookSearchForm,
    DishSearchForm,
    DishTypeSearchForm,
    IngredientSearchForm
)


class IndexView(LoginRequiredMixin, generic.ListView):
    """
    Handles HTTP requests to the main page,
    displaying the three most recently updated dishes.
    """
    template_name = "kitchen/index.html"
    model = Dish
    context_object_name = "dishes"
    queryset = Dish.objects.all().order_by("-updated_at")[:3] \
        .prefetch_related("ingredients")
    paginate_by = 3


class LogoutView(generic.View):
    """
    Handles HTTP POST requests to log out the current user and
    redirects them to the login page.
    If the request is GET, it renders the logged out page.
    """
    def post(self, request: HttpRequest) -> HttpResponse:
        logout(request)
        return redirect("login")

    def get(self, request: HttpRequest) -> HttpResponse:
        return render(request, "registration/logged_out.html")


class CookListView(LoginRequiredMixin, generic.ListView):
    template_name = "kitchen/all_cooks.html"
    model = Cook
    context_object_name = "cooks"
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs) -> dict[Any]:
        context = super(CookListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = CookSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self) -> QuerySet[Cook]:
        queryset = get_user_model().objects.all()
        form = CookSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "kitchen/cook_detail.html"
    model = Cook
    context_object_name = "cook"


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    template_name = "kitchen/cook_form.html"
    form_class = CookCreationForm
    success_url = reverse_lazy("kitchen:cooks-page")

    def get_context_data(self, **kwargs) -> dict[Any]:
        context = super().get_context_data(**kwargs)
        context["page"] = self.request.GET.get("page", 1)
        return context


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    template_name = "kitchen/cook_form.html"
    form_class = CookUpdateForm
    context_object_name = "cook"

    def get_success_url(self) -> str:
        return reverse(
            "kitchen:cook-detail-page", 
            kwargs={"slug": self.object.slug}
        )


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    template_name = "kitchen/cook_confirm_delete.html"
    success_url = reverse_lazy("kitchen:cooks-page")


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    template_name = "kitchen/dishes_list.html"
    context_object_name = "dishes"
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs) -> dict[Any]:
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self) -> QuerySet[Dish]:
        queryset = Dish.objects.all().prefetch_related("ingredients")
        form = DishSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish
    template_name = "kitchen/dish_detail.html"
    context_object_name = "dish"


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    template_name = "kitchen/dish_form.html"
    success_url = reverse_lazy("kitchen:dishes-page")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    template_name = "kitchen/dish_form.html"
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dishes-page")
    context_object_name = "dish"


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    template_name = "kitchen/dish_confirm_delete.html"
    success_url = reverse_lazy("kitchen:dishes-page")


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    template_name = "kitchen/dish_type_list.html"
    context_object_name = "dish_types"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs) -> dict[Any]:
        context = super(DishTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishTypeSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self) -> QuerySet[DishType]:
        queryset = DishType.objects.all()
        form = DishTypeSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    template_name = "kitchen/dish_type_form.html"
    success_url = reverse_lazy("kitchen:dish-types-page")
    context_object_name = "dish_type"


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    template_name = "kitchen/dish_type_form.html"
    success_url = reverse_lazy("kitchen:dish-types-page")
    context_object_name = "dish_type"


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    template_name = "kitchen/dish_type_confirm_delete.html"
    success_url = reverse_lazy("kitchen:dish-types-page")


class IngredientListView(LoginRequiredMixin, generic.ListView):
    model = Ingredient
    template_name = "kitchen/ingredient_list.html"
    context_object_name = "ingredients"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs) -> dict[Any]:
        context = super(IngredientListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = IngredientSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self) -> QuerySet[Ingredient]:
        queryset = Ingredient.objects.all()
        form = IngredientSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class IngredientCreateView(LoginRequiredMixin, generic.CreateView):
    model = Ingredient
    fields = "__all__"
    template_name = "kitchen/ingredient_form.html"
    success_url = reverse_lazy("kitchen:ingredients-page")
    context_object_name = "ingredient"


class IngredientUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Ingredient
    fields = "__all__"
    template_name = "kitchen/ingredient_form.html"
    success_url = reverse_lazy("kitchen:ingredients-page")
    context_object_name = "ingredient"


class IngredientDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Ingredient
    template_name = "kitchen/ingredient_confirm_delete.html"
    success_url = reverse_lazy("kitchen:ingredients-page")


class ToggleAssignToDishView(generic.View):
    def post(self, request: HttpRequest, pk: int) -> HttpResponseRedirect:
        cook = get_user_model().objects.get(id=request.user.id)
        if Dish.objects.get(id=pk) in cook.dishes.all():
            cook.dishes.remove(pk)
        else:
            cook.dishes.add(pk)
        return HttpResponseRedirect(
            reverse_lazy(
                "kitchen:dish-detail-page",
                args=[pk]
            )
        )

kitchen/templates/kitchen/all_cooks.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Cooks
{% endblock %}

{% block css_files %}
  <link rel="stylesheet" href="{% static "kitchen/search_form.css" %}">
  <link rel="stylesheet" href="{% static "kitchen/all_cooks.css" %}">
  <link rel="stylesheet" href="{% static "kitchen/pagination.css" %}">
{% endblock %}

{% block content %}
  <section id="all-cooks">
    <div class="header">
      <h2>Cooks</h2>
      {% include "kitchen/includes/search_form.html" %}
      <a href="{% url "kitchen:cook-create" %}?page={{ request.GET.page }}" 
      class="btn-create">
        Create
      </a>
    </div>
    <div class="cook-cards">
      {% for cook in cooks %}
        <a href="{{ cook.get_absolute_url }}" class="cook-card">
          {% include "kitchen/includes/cook_preview.html" %}
        </a>
      {% endfor %}
    </div>
  </section>
{% endblock %}

{% block pagination %}
  {% include "kitchen/includes/pagination.html" %}
{% endblock pagination %}

kitchen/templates/kitchen/cook_confirm_delete.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Delete Cook
{% endblock %}

{% block css_files %}
  <link rel="stylesheet" 
  href="{% static "kitchen/cook_confirm_delete.css" %}">
{% endblock css_files %}

{% block content %}
  <section id="delete-confirmation">
    <h1>Delete Cook?</h1>
    <p>
      Are you sure you want to delete this cook? This action cannot be undone.
    </p>
    <form action="" method="post">
      {% csrf_token %}
      <div class="form-actions">
        <input type="submit" value="Yes" class="btn btn-delete">
        <button type="button" onclick="history.back();" 
        class="btn btn-cancel">
          Cancel
        </button>
      </div>
    </form>
  </section>
{% endblock content %}

kitchen/templates/kitchen/cook_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {{ cook.full_name }}
{% endblock %}

{% block css_files %}
  <link rel="stylesheet" href="{% static "kitchen/cook_detail.css" %}">
{% endblock %}

{% block content %}
  <section id="summary">
    <div class="cook-details">
      <h3>{{ cook.full_name }}</h3>
      <p><strong>Username:</strong> {{ cook.username }}</p>
      <p><strong>
        Years of Experience:</strong> {{ cook.years_of_experience }}
      </p>
      <address>
        <strong>
          Email: 
        </strong><a href="mailto:{{ cook.email }}">{{ cook.email }}</a>
      </address>
      <p><strong>Bio:</strong></p>
      <p>{{ cook.bio|linebreaks }}</p>
    </div>
    <article>
      <img src="
      {% if cook.profile_picture %}{{ cook.profile_picture.url }}
      {% else %}{% static "kitchen/images/default_profile_picture.jpg" %}
      {% endif %}" alt="{{ cook.username }}">
      <div class="actions">
        <a href="{% url "kitchen:cook-update" cook.slug %}" class="btn">
          Update
        </a>
        <a href="{% url "kitchen:cook-delete" cook.slug %}" 
        class="btn btn-delete">
          Delete
        </a>
      </div>
    </article>
  </section>

  <section id="all-dishes">
    <h2>Dishes by {{ cook.full_name }}</h2>
    <div class="dish-cards">
      {% for dish in cook.dishes.all %}
        <a href="{{ dish.get_absolute_url }}" class="dish-card">
          {% include "kitchen/includes/dish_card.html" %}
        </a>
      {% empty %}
        <p id="no-dishes">No dishes found.</p>
      {% endfor %}
    </div>
  </section>
{% endblock %}

kitchen/templates/kitchen/cook_form.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {{ object|yesno:"Update,Create" }} Cook
{% endblock %}

{% block css_files %}
  <link rel="stylesheet" href="{% static "kitchen/cook_form.css" %}">
{% endblock %}

{% block content %}
  <section id="cook-form-section">
    <h2>{{ object|yesno:"Update,Create" }} Cook</h2>
    <form method="post" enctype="multipart/form-data" 
    class="cook-form" novalidate>
      {% csrf_token %}
      {{ form.as_p }}
      <div class="form-actions">
        <button type="submit" 
        class="btn">{{ object|yesno:"Update,Create" }}</button>
        {% if cook %}
          <a href="{{ cook.get_absolute_url }}" class="btn btn-cancel">
            Cancel
          </a>
        {% else %}
          <a href="{% url "kitchen:cooks-page" %}?page={{ page }}" 
          class="btn btn-cancel">
            Cancel
          </a>
        {% endif %}
      </div>
    </form>
  </section>
{% endblock %}

kitchen/templates/kitchen/dish_confirm_delete.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Delete Dish
{% endblock %}

{% block css_files %}
  <link rel="stylesheet" 
  href="{% static "kitchen/cook_confirm_delete.css" %}">
{% endblock css_files %}

{% block content %}
  <section id="delete-confirmation">
    <h1>Delete Dish?</h1>
    <p>
      Are you sure you want to delete this dish? This action cannot be undone.
    </p>
    <form action="" method="post">
      {% csrf_token %}
      <div class="form-actions">
        <input type="submit" value="Yes" class="btn btn-delete">
        <button type="button" onclick="history.back();" 
        class="btn btn-cancel">
          Cancel
        </button>
      </div>
    </form>
  </section>
{% endblock content %}

kitchen/templates/kitchen/dish_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {{ dish.name }}
{% endblock %}

{% block css_files %}
  <link rel="stylesheet" href="{% static "kitchen/dish_detail.css" %}">
{% endblock %}

{% block content %}
  <section id="container">
    <div class="dish-details">
      <h1>{{ dish.name }}</h1>
      <article>
        <img src="{{ dish.image.url }}" alt="{{ dish.name }}">
      </article>
      <p>{{ dish.description }}</p>
      <p><strong>Price:</strong> ${{ dish.price }}</p>
      <p><strong>Type:</strong> {{ dish.dish_type.name }}</p>
      <p><strong>Cooks:</strong>
        {% for cook in dish.cooks.all %}
          {{ cook.full_name }}{% if not forloop.last %}, {% endif %}
        {% endfor %}
      </p>
      <h3>Ingredients:</h3>
      <ul>
        {% for ingredient in dish.ingredients.all %}
          <li>
            {{ ingredient.name }}{% if not forloop.last %}, {% endif %}
          </li>
          {% endfor %}
      </ul>

      <div class="actions">
        <a href="{% url "kitchen:dish-update" dish.id %}" class="btn">
          Update
        </a>
        <a href="{% url "kitchen:dish-delete" dish.id %}" 
        class="btn btn-delete">
          Delete
        </a>
        <form 
        method="post" 
        action="{% url "kitchen:toggle-dish-assign" pk=dish.id %}">
          {% csrf_token %}
          {% if dish in user.dishes.all %}
            <button type="submit" class="btn-unassign btn-update-assign">
              Unassign me from this dish
            </button>
          {% else %}
            <button type="submit" class="btn-assign btn-update-assign">
              Assign me to this dish
            </button>
          {% endif %}
        </form>
      </div>
    </div>
  </section>
{% endblock %}

kitchen/templates/kitchen/dish_form.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {{ object|yesno:"Update,Create" }} Dish
{% endblock %}

{% block css_files %}
  <link rel="stylesheet" href="{% static "kitchen/dish_form.css" %}">
{% endblock %}

{% block content %}
  <section id="dish-form-section">
    <h2>{{ object|yesno:"Update,Create" }} Dish</h2>
    <form method="post" enctype="multipart/form-data" 
    class="dish-form" novalidate>

      {% csrf_token %}
      {{ form.non_field_errors }}
      {{ form.name.errors }}

      <div class="form-group">
        {{ form.name.label_tag }} {{ form.name }}
      </div>
      {{ form.description.errors }}
      <div class="form-group">
        {{ form.description.label_tag }} {{ form.description }}
      </div>
      {{ form.price.errors }}
      <div class="form-group">
        {{ form.price.label_tag }} {{ form.price }}
      </div>
      {{ form.dish_type.errors }}
      <div class="form-group">
        {{ form.dish_type.label_tag }} {{ form.dish_type }}
      </div>
      {{ form.cooks.errors }}
      <div class="form-group">
        {{ form.cooks.label_tag }} {{ form.cooks }}
      </div>
      <div class="scrollable-checkboxes">
        {{ form.ingredients.errors }}
        {{ form.ingredients.label_tag }} {{ form.ingredients }}
      </div>
      {{ form.image.errors }}
      <div class="form-group">
        {{ form.image.label_tag }} {{ form.image }}
      </div>

      <div class="form-actions">
        <button type="submit" class="btn">
          {{ object|yesno:"Update,Create" }}
        </button>
        {% if object %}
          <a href="{{ dish.get_absolute_url }}" class="btn btn-cancel">
            Cancel
          </a>
        {% else %}
          <a href="{% url "kitchen:dishes-page" %}?page={{ page }}" 
          class="btn btn-cancel">
            Cancel
          </a>
        {% endif %}
      </div>
    </form>
  </section>
{% endblock %}

kitchen/templates/kitchen/dish_type_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Dish Types
{% endblock %}

{% block css_files %}
  <link rel="stylesheet" href="{% static "kitchen/search_form.css" %}">
  <link rel="stylesheet" href="{% static "kitchen/dish_type_list.css" %}">
  <link rel="stylesheet" href="{% static "kitchen/pagination.css" %}">
{% endblock css_files %}

{% block content %}
  <div class="header">
    <h2>Dish Types</h2>
    {% include "kitchen/includes/search_form.html" %}
    <a href="{% url "kitchen:dish-type-create" %}" class="btn-create">
      Create
    </a>
  </div>
  <section class="container">
    <div class="dish-types">
      {% if dish_types %}
        {% for dish_type in dish_types %}
          <section class="dish-type">
            <h2>{{ dish_type.name }}</h2>
            {% if dish_type.description %}
              <p>{{ dish_type.description }}</p>
            {% else %}
              <p>No description added.</p>
            {% endif %}
            <div class="actions">
              <a href="{% url "kitchen:dish-type-update" dish_type.id %}" 
              class="btn">
                Update
              </a>
              <a href="{% url 'kitchen:dish-type-delete' dish_type.id %}" 
              class="btn btn-delete">
                Delete
              </a>
            </div>
          </section>
        {% endfor %}
      {% else %}
        <p>No dish types found.</p>
      {% endif %}
    </div>
  </section>
{% endblock content %}

{% block pagination %}
  {% include "kitchen/includes/pagination.html" %}
{% endblock pagination %}

kitchen/templates/kitchen/dishes_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Dishes
{% endblock %}

{% block css_files %}
  <link rel="stylesheet" href="{% static "kitchen/search_form.css" %}">
  <link rel="stylesheet" href="{% static "kitchen/dishes_list.css" %}">
  <link rel="stylesheet" href="{% static "kitchen/pagination.css" %}">
{% endblock %}

{% block content %}
  <section id="all-dishes">
    <div class="header">
      <h2>Dishes</h2>
      {% include "kitchen/includes/search_form.html" %}
      <a href="{% url "kitchen:dish-create" %}" class="btn-create">
        Create
      </a>
    </div>
    <div class="dish-cards">
      {% for dish in dishes %}
        <a href="{{ dish.get_absolute_url }}" class="dish-card">
          {% include "kitchen/includes/dish_card.html" %}
        </a>
      {% endfor %}
    </div>
  </section>
{% endblock %}

{% block pagination %}
  {% include "kitchen/includes/pagination.html" %}
{% endblock pagination %}

kitchen/templates/kitchen/ingredient_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Ingredients
{% endblock %}

{% block css_files %}
  <link rel="stylesheet" href="{% static "kitchen/search_form.css" %}">
  <link rel="stylesheet" href="{% static "kitchen/ingredient_list.css" %}">
  <link rel="stylesheet" href="{% static "kitchen/pagination.css" %}">
{% endblock css_files %}

{% block content %}
  <div class="header">
    <h2>Ingredients</h2>
    {% include "kitchen/includes/search_form.html" %}
    <a href="{% url "kitchen:ingredient-create" %}" class="btn-create">
      Create
    </a>
  </div>
  <section class="container">
    <div class="ingredients">
      {% if ingredients %}
        {% for ingredient in ingredients %}
          <section class="ingredient">
            <h2>{{ ingredient.name }}</h2>
            {% if ingredient.description %}
              <p>{{ ingredient.description }}</p>
            {% else %}
              <p>No description added.</p>
            {% endif %}
            <div class="actions">
              <a href="{% url "kitchen:ingredient-update" ingredient.id %}" 
              class="btn">
                Update
              </a>
              <a href="{% url "kitchen:ingredient-delete" ingredient.id %}" 
              class="btn btn-delete">
                Delete
              </a>
            </div>
          </section>
        {% endfor %}
      {% else %}
        <p>No ingredients found.</p>
      {% endif %}
    </div>
  </section>
{% endblock content %}

{% block pagination %}
  {% include "kitchen/includes/pagination.html" %}
{% endblock pagination %}