kitchen/urls.py
from django.urls import path

from kitchen import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="main-page"),
    path("cooks/", views.CookListView.as_view(), name="cooks-page"),
    path(
        "cooks/create/",
        views.CookCreateView.as_view(),
        name="cook-create"
    ),
    path(
        "cooks/<slug:slug>/",
        views.CookDetailView.as_view(),
        name="cook-detail-page"
    ),
    path(
        "cooks/<slug:slug>/update/",
        views.CookUpdateView.as_view(),
        name="cook-update"
    ),
    path(
        "cooks/<slug:slug>/delete/",
        views.CookDeleteView.as_view(),
        name="cook-delete"
    ),
    path(
        "dishes/",
        views.DishListView.as_view(),
        name="dishes-page"
    ),
    path(
        "dishes/<int:pk>/",
        views.DishDetailView.as_view(),
        name="dish-detail-page"
    ),
    path(
        "dishes/create/",
        views.DishCreateView.as_view(),
        name="dish-create"
    ),
    path(
        "dishes/<int:pk>/update/",
        views.DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dishes/<int:pk>/delete/",
        views.DishDeleteView.as_view(),
        name="dish-delete"
    ),
    path(
        "dishes/<int:pk>/assign/",
        views.ToggleAssignToDishView.as_view(),
        name="toggle-dish-assign"
    ),
    path(
        "dish_types/",
        views.DishTypeListView.as_view(),
        name="dish-types-page"
    ),
    path(
        "dish_types/create/",
        views.DishTypeCreateView.as_view(),
        name="dish-type-create"
    ),
    path(
        "dish_types/<int:pk>/update/",
        views.DishTypeUpdateView.as_view(),
        name="dish-type-update"
    ),
    path(
        "dish_types/<int:pk>/delete/",
        views.DishTypeDeleteView.as_view(),
        name="dish-type-delete"
    ),
    path(
        "ingredients/",
        views.IngredientListView.as_view(),
        name="ingredients-page"
    ),
    path(
        "ingredients/create/",
        views.IngredientCreateView.as_view(),
        name="ingredient-create"
    ),
    path(
        "ingredients/<int:pk>/update/",
        views.IngredientUpdateView.as_view(),
        name="ingredient-update"
    ),
    path(
        "ingredients/<int:pk>/delete/",
        views.IngredientDeleteView.as_view(),
        name="ingredient-delete"
    ),
]

app_name = "kitchen"

restaurant_mate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from debug_toolbar.toolbar import debug_toolbar_urls

from kitchen.views import LogoutView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += debug_toolbar_urls()

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>
    {% block title %}
    {% endblock %} 
  </title>
  <link rel="stylesheet" href="{% static "app.css" %}">
  {% block css_files %}
  {% endblock %}
</head>

<body>
  <header id="main-navigation">
    <nav>
      <span>
        <a href="{% url "kitchen:main-page" %}">Home</a>
        <a href="{% url "kitchen:cooks-page" %}">Cooks</a>
        <a href="{% url "kitchen:dishes-page" %}">Dishes</a>
        <a href="{% url "kitchen:dish-types-page" %}">Dish Types</a>
        <a href="{% url "kitchen:ingredients-page" %}">Ingredients</a>
      </span>
    </nav>
    <div>
      {% if user.is_authenticated %}
        <span class="user-info">Welcome, {{ user.username }}!</span>
        <a href="{% url "logout" %}">Logout</a>
      {% else %}
        <a href="{% url 'login' %}">Login</a>
      {% endif %}
    </div>
  </header>

  {% block content %}
  {% endblock %}

  {% block pagination %}
  {% endblock pagination %}
</body>
</html>